# @name регистрация пользователя по почте и паролю
POST {{host}}/register
Accept: application/json
Content-Type: application/json

{
  "name": "Кузя Лакомкин",
  "email": "artem1278495@gmail.com",
  "password": "123456",
  "password_confirmation": "123456"
}

###
# @name авторизация
POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "artem1278495@gmail.com",
  "password": "123456"
}


###
# @name выход
POST {{host}}/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name обновить токен
POST {{host}}/refresh
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###