# @name создание поста
POST {{host}}/posts
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "topic": "Охота и рыбалка",
  "title": "Ловля карася на карпа",
  "content": "Ловля карася на карпа.Ловля карася на карпа.Ловля карася на карпа.Ловля карася на карпа?",
  "published_at": "2024-08-04T14:33:13.000000Z"
}

###

# @name обновление поста
PATCH {{host}}/posts/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "topic": "Охота и рыбалка",
  "title": "Ловля карася на сома",
  "content": "Ловля карася на карпа.Ловля карася на карпа.Ловля карася на карпа.Ловля карася на карпа?",
}

###

# @name удаление поста
DELETE {{host}}/posts/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name просмотр поста
GET {{host}}/posts/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}
###

# @name список постов
GET {{host}}/posts/
Accept: application/json
Content-Type: application/json

{
  "order_by": "asc",
  "field": "updated_at",
  "begin_date": "2020-08-04T14:33:13.000000Z",
  "end_date": "2025-08-04T14:33:13.000000Z"
}